services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/department_db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: docker.arvancloud.ir/postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=department_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 